# 4-2. Bow
- Bag of Words
- 해당 문서 내에서 단어들의 등장 빈도 표기

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

 - bow에는 vector.vocabulary_의 인덱스 순서대로 빈도수가 표기됨.
 - 즉, love와 you는 2번 씩 등장함

In [17]:
corpus = ['you know I want your love. because I love you']
vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print('bag of words vector: ', vector.fit_transform(corpus).toarray())

# 각 단어의 인덱스
print('voacbulary: ', vector.vocabulary_)
print(sorted(vector.vocabulary_.items(), key=lambda x:x[1]))

bag of words vector:  [[1 1 2 1 2 1]]
voacbulary:  {'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}
[('because', 0), ('know', 1), ('love', 2), ('want', 3), ('you', 4), ('your', 5)]


불용어 제외 가능

In [19]:
vector2 = CountVectorizer(stop_words='english') # 자체 불용어

from nltk.corpus import stopwords
stop_words = stopwords.words('english')
vector3 = CountVectorizer(stop_words=stop_words) # nltk 불용어

# 4-3. DTM (Document-Term Matrix)
- 문서 단어 행렬
- TF(문서 내 단어 등장 횟수)가 원소

# 4-4.Tf-IDF

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['you know I want your love','I like you','what should I do']

vector = CountVectorizer()

# DTM
dtm = vector.fit_transform(corpus).toarray()
print(dtm)

# dictionary
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
corpus = ['you know I want your love','I like you','what should I do']

tfidfv = TfidfVectorizer()

# tf-idf
print(tfidfv.fit_transform(corpus).toarray())

# dictionary
print(tfidfv.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
